# Generated by Django 3.0.6 on 2020-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20200517_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
