# Generated by Django 3.0.6 on 2020-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_photo_fullsizeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.SET(''), to='photography.Camera'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=models.SET(''), to='photography.Lens'),
        ),
    ]
