# Generated by Django 3.0.6 on 2020-05-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_auto_20200518_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='fullSizeUrl',
            new_name='thumbnailUrl',
        ),
    ]
