# Generated by Django 3.0.6 on 2020-05-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_auto_20200519_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='highlightImage',
        ),
    ]
